#!/usr/bin/env python3
"""
Regenerate test/inflate_stream/fixtures/InflateStreamFixtures.h.

Two deterministic zlib-compressed payloads:
- SMALL: fits in one InflateStream one-shot read.
- STREAMING: exceeds the 32 KB ring buffer, forcing multiple wraparounds.

Only the compressed bytes and an FNV-1a64 digest of the original are
embedded (not the decompressed payload itself) to keep the header small.
"""

import random
import zlib

OUTPUT_PATH = "test/inflate_stream/fixtures/InflateStreamFixtures.h"


def fnv1a64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def emit_blob(f, name: str, original: bytes, level: int) -> None:
    compressed = zlib.compress(original, level)
    digest = fnv1a64(original)
    f.write(f"constexpr size_t {name}_ORIGINAL_LEN = {len(original)};\n")
    f.write(f"constexpr uint64_t {name}_ORIGINAL_FNV1A64 = 0x{digest:016x}ULL;\n")
    f.write(f"constexpr size_t {name}_COMPRESSED_LEN = {len(compressed)};\n")
    f.write(f"constexpr uint8_t {name}_COMPRESSED[] = {{\n")
    for i in range(0, len(compressed), 16):
        chunk = compressed[i : i + 16]
        f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write("};\n\n")


def main() -> None:
    random.seed(42)

    small = b"The quick brown fox jumps over the lazy dog. " * 50

    words = [
        "lorem", "ipsum", "dolor", "sit", "amet", "consectetur",
        "adipiscing", "elit", "sed", "do",
    ]
    streaming = " ".join(random.choice(words) for _ in range(20000)).encode()
    assert len(streaming) > 32768, "streaming fixture must exceed the 32KB ring buffer"

    with open(OUTPUT_PATH, "w") as f:
        f.write("// Generated by scripts/gen_inflate_stream_fixture.py -- do not hand-edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n#include <cstdint>\n\n")
        emit_blob(f, "SMALL", small, level=9)
        emit_blob(f, "STREAMING", streaming, level=6)

    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
